// Dev-only tool for designing the world map visually.
// Rendered only when import.meta.env.DEV is true (removed from prod builds).
//
// Workflow:
//   1. Adjust Tile ID, Col, Row, Width, Height in the Leva panel
//   2. A yellow ghost shows exactly what will be stamped
//   3. Click "Stamp" to write tiles into the atlas (instant, no reload)
//   4. When happy with the result, click "Export Map"
//   5. Paste the clipboard output into src/data/worldMap.ts and commit

import * as THREE from 'three'
import { useControls, button } from 'leva'
import { COLS, ROWS, MAP, writeTile } from './FloorMap'

const TILE_SIZE = 1
const OX = -(COLS * TILE_SIZE) / 2
const OZ = -(ROWS * TILE_SIZE) / 2

interface Props {
  uvAttrRef: React.MutableRefObject<THREE.InstancedBufferAttribute | null>
}

export default function PlacementTool({ uvAttrRef }: Props) {
  const { col, row, width, height } = useControls('Place Tiles', {
    tileId: { value: 49, min: 1, max: 64, step: 1, label: 'Tile ID (1–64)' },
    col:    { value: 0, min: 0, max: COLS - 1, step: 1, label: 'Col (left→right)' },
    row:    { value: 0, min: 0, max: ROWS - 1, step: 1, label: 'Row (top→bottom)' },
    width:  { value: 1, min: 1, max: 20, step: 1, label: 'Width' },
    height: { value: 1, min: 1, max: 20, step: 1, label: 'Height' },

    Stamp: button((get) => {
      const attr = uvAttrRef.current
      if (!attr) return
      const c  = get('Place Tiles.col')    as number
      const r  = get('Place Tiles.row')    as number
      const w  = get('Place Tiles.width')  as number
      const h  = get('Place Tiles.height') as number
      const id = get('Place Tiles.tileId') as number
      for (let dr = 0; dr < h; dr++) {
        for (let dc = 0; dc < w; dc++) {
          writeTile(c + dc, r + dr, id, attr)
        }
      }
    }),

    'Export Map': button((get) => {
      const tileValues = Array.from(MAP).join(',')

      // Read current zone positions from Leva's global store.
      const zones = ['Dev', 'Design', 'Game'].map((label) => {
        const f = `Zone: ${label}`
        return {
          key:    label.toLowerCase(),
          x:      get(`${f}.x`)      as number,
          z:      get(`${f}.z`)      as number,
          width:  get(`${f}.width`)  as number,
          height: get(`${f}.height`) as number,
        }
      })

      const snippet =
        `// Auto-generated by PlacementTool — paste into src/data/worldMap.ts\n` +
        `export const WORLD_MAP = new Uint8Array([${tileValues}])\n\n` +
        `export const WORLD_ZONES = ${JSON.stringify(zones, null, 2)}\n`

      navigator.clipboard?.writeText(snippet).catch(() => {})
      localStorage.removeItem('gather_map_draft')
    }),

    'Clear Draft': button(() => {
      localStorage.removeItem('gather_map_draft')
    }),
  })

  // Ghost — yellow transparent plane showing the exact stamp footprint.
  const ghostX = OX + (col + width / 2) * TILE_SIZE
  const ghostZ = OZ + (row + height / 2) * TILE_SIZE

  return (
    <mesh
      position={[ghostX, 0.01, ghostZ]}
      rotation={[-Math.PI / 2, 0, 0]}
    >
      <planeGeometry args={[width * TILE_SIZE, height * TILE_SIZE]} />
      <meshBasicMaterial color="yellow" transparent opacity={0.35} depthTest={false} />
    </mesh>
  )
}
