#!/usr/bin/env node
/**
 * Extract tile layer data from assets/map1/map 1.tmx and write TypeScript
 * constants ready to paste into client/src/data/worldMap.ts.
 *
 * Usage:
 *   node scripts/extract-tmx.mjs
 */

import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const TMX_PATH = join(ROOT, 'assets', 'map1', 'map 1.tmx')
const OUT_PATH = join(ROOT, 'client', 'src', 'data', '_tmx_extracted.ts')

const COLS = 60
const ROWS = 60
const TOTAL = COLS * ROWS

// ─── TMX tileset firstgid constants ─────────────────────────────────────────
const FIELDS_FIRSTGID = 1   // FieldsTileset.png   – 64 tiles (8×8)
const FIELDS_COUNT    = 64
const SUMMER_FIRSTGID = 83  // summer_plains tiles.png – 156 tiles (13×12)
const SUMMER_COUNT    = 156

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Strip Tiled flip/rotate flags from a GID (bits 31, 30, 29). */
function stripFlipFlags(gid) {
  return gid & 0x1FFFFFFF
}

/**
 * Extract the CSV data block from the named layer inside the TMX string.
 * Handles layers inside <group> elements too.
 */
function extractLayerCSV(tmx, layerName) {
  // Match <layer ... name="layerName" ...> ... <data ...>CSV</data>
  const re = new RegExp(
    `<layer[^>]+name="${layerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[^>]*>[\\s\\S]*?<data[^>]*>([\\s\\S]*?)<\\/data>`,
  )
  const m = tmx.match(re)
  if (!m) throw new Error(`Layer "${layerName}" not found in TMX`)
  return m[1]
}

/** Parse a 60×60 CSV block into a flat number[] of length 3600. */
function parseCSV(csv) {
  const values = []
  for (const line of csv.split('\n')) {
    const trimmed = line.trim().replace(/,$/, '')
    if (!trimmed) continue
    for (const tok of trimmed.split(',')) {
      values.push(parseInt(tok.trim(), 10))
    }
  }
  if (values.length !== TOTAL) {
    throw new Error(`Expected ${TOTAL} values, got ${values.length}`)
  }
  return values
}

/** Format a flat number[] as a multi-line Uint8Array literal (one row per line). */
function formatUint8Array(name, data) {
  const lines = [`export const ${name} = new Uint8Array([`]
  for (let r = 0; r < ROWS; r++) {
    const row = data.slice(r * COLS, (r + 1) * COLS)
    lines.push('  ' + row.join(',') + (r < ROWS - 1 ? ',' : ''))
  }
  lines.push('])')
  return lines.join('\n')
}

// ─── Parse TMX ──────────────────────────────────────────────────────────────

const tmx = readFileSync(TMX_PATH, 'utf-8')

// Layer 1: base ground (FieldsTileset, firstgid=1, tile IDs 1–64)
const layer1Raw = parseCSV(extractLayerCSV(tmx, 'Tile Layer 1'))
const worldMap = layer1Raw.map(gid => {
  if (gid === 0) return 1 // default to dirt if somehow empty
  const id = stripFlipFlags(gid)
  if (id < FIELDS_FIRSTGID || id > FIELDS_FIRSTGID + FIELDS_COUNT - 1) return 1
  return id // already 1-indexed, fits in Uint8Array (1–64)
})

// Road stones: overlay using summer_plains tileset (firstgid=83, local IDs 1–156)
const roadRaw = parseCSV(extractLayerCSV(tmx, 'road stones'))
const roadStonesMap = roadRaw.map(gid => {
  if (gid === 0) return 0
  const id = stripFlipFlags(gid)
  if (id < SUMMER_FIRSTGID || id >= SUMMER_FIRSTGID + SUMMER_COUNT) return 0
  return id - SUMMER_FIRSTGID + 1 // 1-indexed local ID (1–156), 0 = empty
})

// ─── Stats ───────────────────────────────────────────────────────────────────

const uniqueBase  = [...new Set(worldMap)].sort((a, b) => a - b)
const uniqueRoad  = [...new Set(roadStonesMap)].sort((a, b) => a - b)
const roadNonZero = roadStonesMap.filter(v => v !== 0).length

console.log(`Layer 1  — unique tile IDs : ${uniqueBase.join(', ')}`)
console.log(`Road     — unique local IDs: ${uniqueRoad.filter(v => v > 0).join(', ')}`)
console.log(`Road     — non-zero tiles  : ${roadNonZero} / ${TOTAL}`)

// ─── Output ──────────────────────────────────────────────────────────────────

const header = [
  '// Auto-generated by scripts/extract-tmx.mjs — do not edit by hand.',
  '// Re-run the script whenever assets/map1/map 1.tmx changes.',
  '',
  '// WORLD_MAP: base ground layer (FieldsTileset tile IDs 1–64).',
  '// Source: "Tile Layer 1" in map 1.tmx.',
].join('\n')

const footer = [
  '',
  '// ROAD_STONES_MAP: summer_plains overlay (local tile IDs 1–156, 0 = empty).',
  '// Source: "road stones" layer in map 1.tmx.  firstgid=83 stripped.',
  '// Flip flags (bits 29–31) are stripped — corners may look slightly off.',
].join('\n')

const output = [
  header,
  '',
  formatUint8Array('WORLD_MAP', worldMap),
  footer,
  '',
  formatUint8Array('ROAD_STONES_MAP', roadStonesMap),
  '',
].join('\n')

writeFileSync(OUT_PATH, output)
console.log(`\nWrote ${OUT_PATH}`)
